### ISSUE TITLE
Use the `atom-workspace` tag instead of the `workspace` class.

### ISSUE THREAD

**Issue by maxzhang** [unDemian/clipboard-history#14]
In menus/clipboard-history.cson: Use the `atom-workspace` tag instead of the `workspace` class.

**Comment by unDemian** [comment]
This is already updated, what version do you use?

**Comment by vforvova** [comment]
The same problem.
About version. Version of your package in apm is 0.6.3 and it is actual. My version was 0.6.1. I had tried to update it, and Atom said that there were no new versions. If I delete clipboard-history completely and reinstall it, it anyway has version 0.6.1. I'm not sure that the problem is on your side, but it will be great if you check it. May be something is wrong with your account on atom.io?

**Comment by unDemian** [comment]
Hmm... this is weird, all looks good on my side. The atom.io version is 0.6.3 and mine was updated correctly. Are you sure you didn't move it to development or something..

**Comment by vforvova** [comment]
Thank you! Your yesterday commit also fixed my problem with updates!
